@isTest
public class companytest {
    @isTest
    static void testcom(){
        OlderAccountsUtility.Company('testComp');
    }
    @isTest
    static void testmapmethod(){
        OlderAccountsUtility.returnmap('test','case');
        
    }
    @isTest
    static void testStringmethod(){
        OlderAccountsUtility.returnlist('aayu','monika');
        
    }
    @isTest
    static void testStringSet(){
        OlderAccountsUtility.returnset('xyz','abc');
            
    }
    
    

}